name: deepfri
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2022.12.7
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.2
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.15
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy-base=1.21.5
  - openssl=1.1.1w
  - packaging=22.0
  - pandas=1.3.5
  - pcre2=10.42
  - pillow=9.4.0
  - pip=22.3.1
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.7.16
  - python-dateutil=2.8.2
  - pytz=2022.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.45.3
  - tk=8.6.14
  - toml=0.10.2
  - tornado=6.2
  - typing_extensions=4.4.0
  - wheel=0.38.4
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - biopython==1.76
      - cachetools==5.3.3
      - charset-normalizer==3.3.2
      - decorator==5.1.1
      - gast==0.3.3
      - google-auth==2.29.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.62.2
      - h5py==2.10.0
      - idna==3.7
      - importlib-metadata==6.7.0
      - joblib==1.3.2
      - keract==4.5.1
      - keras-preprocessing==1.1.2
      - markdown==3.4.4
      - markupsafe==2.1.5
      - networkx==2.4
      - numpy==1.18.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==3.20.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-learn==0.23.1
      - scipy==1.7.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.3.0
      - tensorflow-gpu==2.3.1
      - termcolor==2.3.0
      - threadpoolctl==3.1.0
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - zipp==3.15.0
